################################################################################
MLI_FILE		= node_nightmare.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= ocaml_node_nightmare
################################################################################
